In [9]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path
import re
import xml.etree.ElementTree as ET
from functools import reduce
import openpyxl
from scipy.optimize import minimize_scalar
import numpy as np
import glob

pd.set_option('display.max_columns', None)

# Schooling

In [10]:
import requests
import pandas as pd
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

def fetch_worldbank_indicator(country="ua", indicator="SE.TER.ENRR", start_year=2000, end_year=2024):
    url = f"https://api.worldbank.org/v2/country/{country}/indicator/{indicator}"

    session = requests.Session()
    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=1.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"]
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("https://", adapter)
    session.mount("http://", adapter)

    params = {
        "format": "json",
        "per_page": 200,
        "date": f"{start_year}:{end_year}"
    }

    resp = session.get(url, params=params, timeout=(10, 360))
    resp.raise_for_status()
    data = resp.json()

    rows = data[1]

    df = pd.DataFrame([
        {
            "country": row["country"]["value"],
            "year": int(row["date"]),
            "school_enrollment": row["value"]
        }
        for row in rows if row["value"] is not None
    ])

    return df.sort_values("year").reset_index(drop=True)

school_enrollment = fetch_worldbank_indicator()
school_enrollment

    country  year  school_enrollment
0   Ukraine  2000          50.507118
1   Ukraine  2001          52.910110
2   Ukraine  2002          56.645679
3   Ukraine  2003          60.255322
4   Ukraine  2004          63.440750
5   Ukraine  2005          66.889862
6   Ukraine  2006          71.939812
7   Ukraine  2007          76.262756
8   Ukraine  2008          79.732521
9   Ukraine  2009          82.499252
10  Ukraine  2010          81.908251
11  Ukraine  2011          84.798106
12  Ukraine  2012          83.879900
13  Ukraine  2013          81.532011
14  Ukraine  2014          83.784217
15  Ukraine  2015          76.864656
16  Ukraine  2016          77.039837
17  Ukraine  2017          80.199025
18  Ukraine  2018          81.494672
19  Ukraine  2019          84.481356
20  Ukraine  2020          82.134599
21  Ukraine  2021          75.907944
22  Ukraine  2023          82.553360
23  Ukraine  2024          87.192001

In [11]:
school_enrollment["quarter_period"] = pd.PeriodIndex(
    school_enrollment["year"].astype(str) + "Q4",
    freq="Q"
)

full_quarters = pd.period_range(
    start=f"{school_enrollment['year'].min()}Q1",
    end=f"{school_enrollment['year'].max()}Q4",
    freq="Q"
)

school_enrollment = (
    school_enrollment
    .set_index("quarter_period")[["school_enrollment"]]
    .reindex(full_quarters)
)

school_enrollment["school_enrollment_q_interp"] = (
    school_enrollment["school_enrollment"]
    .interpolate(method="linear", limit_direction="both")
)

school_enrollment = school_enrollment.reset_index().rename(columns={"index": "quarter_period"})
school_enrollment["year_quarter"] = school_enrollment["quarter_period"].astype(str)

school_enrollment = school_enrollment[school_enrollment['year_quarter']>='2010Q1'][["year_quarter", "school_enrollment_q_interp"]]

school_enrollment

   year_quarter  school_enrollment_q_interp
40       2010Q1                   82.351502
41       2010Q2                   82.203752
42       2010Q3                   82.056001
43       2010Q4                   81.908251
44       2011Q1                   82.630715
45       2011Q2                   83.353179
46       2011Q3                   84.075642
47       2011Q4                   84.798106
48       2012Q1                   84.568554
49       2012Q2                   84.339003
50       2012Q3                   84.109451
51       2012Q4                   83.879900
52       2013Q1                   83.292928
53       2013Q2                   82.705956
54       2013Q3                   82.118983
55       2013Q4                   81.532011
56       2014Q1                   82.095063
57       2014Q2                   82.658114
58       2014Q3                   83.221166
59       2014Q4                   83.784217
60       2015Q1                   82.054327
61       2015Q2                   80.324437
62       2015Q3                   78.594546
63       2015Q4                   76.864656
64       2016Q1                   76.908451
65       2016Q2                   76.952247
66       2016Q3                   76.996042
67       2016Q4                   77.039837
68       2017Q1                   77.829634
69       2017Q2                   78.619431
70       2017Q3                   79.409228
71       2017Q4                   80.199025
72       2018Q1                   80.522936
73       2018Q2                   80.846848
74       2018Q3                   81.170760
75       2018Q4                   81.494672
76       2019Q1                   82.241343
77       2019Q2                   82.988014
78       2019Q3                   83.734685
79       2019Q4                   84.481356
80       2020Q1                   83.894667
81       2020Q2                   83.307978
82       2020Q3                   82.721288
83       2020Q4                   82.134599
84       2021Q1                   80.577935
85       2021Q2                   79.021271
86       2021Q3                   77.464607
87       2021Q4                   75.907944
88       2022Q1                   76.738621
89       2022Q2                   77.569298
90       2022Q3                   78.399975
91       2022Q4                   79.230652
92       2023Q1                   80.061329
93       2023Q2                   80.892006
94       2023Q3                   81.722683
95       2023Q4                   82.553360
96       2024Q1                   83.713020
97       2024Q2                   84.872681
98       2024Q3                   86.032341
99       2024Q4                   87.192001

# Other indicator (global economy)

In [12]:
indicators = pd.read_csv("raw_csvs/21-04-26 03_47_45_theglobaleconomy.csv")
indicators = indicators[[
    'Year',
    'Rule of law index (-2.5 weak; 2.5 strong)',
    'Government effectiveness index (-2.5 weak; 2.5 strong)',
    'Corruption Perceptions Index 100 = no corruption',
    'Fiscal freedom index (0-100)', 'Business freedom index (0-100)',
    'Financial freedom index (0-100)',
    'Economic freedom overall index (0-100)'
]]
indicators

,Year,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Fiscal freedom index (0-100),Business freedom index (0-100),Financial freedom index (0-100),Economic freedom overall index (0-100)
0,2010,-0.81,-0.81,24,78.0,39.0,30.0,46.0
1,2011,-0.77,-0.83,23,77.0,47.0,30.0,46.0
2,2012,-0.67,-0.70,26,78.0,46.0,30.0,46.0
3,2013,-0.72,-0.74,25,78.0,48.0,30.0,46.0
4,2014,-0.73,-0.52,26,79.0,60.0,30.0,49.0
5,2015,-0.70,-0.55,27,79.0,59.0,30.0,47.0
6,2016,-0.65,-0.52,29,79.0,57.0,30.0,47.0
7,2017,-0.58,-0.48,30,79.0,62.0,30.0,48.0
8,2018,-0.52,-0.36,32,80.0,63.0,30.0,52.0
9,2019,-0.59,-0.37,30,82.0,66.0,30.0,52.0
10,2020,-0.57,-0.38,33,81.0,61.0,30.0,55.0
11,2021,-0.57,-0.40,32,89.0,64.0,30.0,56.0
12,2022,-0.74,-0.64,33,74.0,61.0,30.0,54.0
13,2023,-0.75,-0.58,36,NaN,NaN,NaN,NaN
14,2024,-0.72,-0.60,35,NaN,NaN,NaN,NaN

In [ ]:
df_q = indicators.loc[indicators.index.repeat(4)].reset_index(drop=True)

df_q["quarter"] = ["Q1", "Q2", "Q3", "Q4"] * len(indicators)
df_q["year_quarter"] = df_q["Year"].astype(str) + df_q["quarter"]

df_q = df_q.drop(columns="quarter")

cols = ["year_quarter"] + [c for c in df_q.columns if c != "year_quarter" and c != "Year"]
df_q = df_q[cols]

df_q

,year_quarter,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Fiscal freedom index (0-100),Business freedom index (0-100),Financial freedom index (0-100),Economic freedom overall index (0-100)
0,2010Q1,-0.81,-0.81,24,78.0,39.0,30.0,46.0
1,2010Q2,-0.81,-0.81,24,78.0,39.0,30.0,46.0
2,2010Q3,-0.81,-0.81,24,78.0,39.0,30.0,46.0
3,2010Q4,-0.81,-0.81,24,78.0,39.0,30.0,46.0
4,2011Q1,-0.77,-0.83,23,77.0,47.0,30.0,46.0
5,2011Q2,-0.77,-0.83,23,77.0,47.0,30.0,46.0
6,2011Q3,-0.77,-0.83,23,77.0,47.0,30.0,46.0
7,2011Q4,-0.77,-0.83,23,77.0,47.0,30.0,46.0
8,2012Q1,-0.67,-0.70,26,78.0,46.0,30.0,46.0
9,2012Q2,-0.67,-0.70,26,78.0,46.0,30.0,46.0
10,2012Q3,-0.67,-0.70,26,78.0,46.0,30.0,46.0
11,2012Q4,-0.67,-0.70,26,78.0,46.0,30.0,46.0
12,2013Q1,-0.72,-0.74,25,78.0,48.0,30.0,46.0
13,2013Q2,-0.72,-0.74,25,78.0,48.0,30.0,46.0
14,2013Q3,-0.72,-0.74,25,78.0,48.0,30.0,46.0
15,2013Q4,-0.72,-0.74,25,78.0,48.0,30.0,46.0
16,2014Q1,-0.73,-0.52,26,79.0,60.0,30.0,49.0
17,2014Q2,-0.73,-0.52,26,79.0,60.0,30.0,49.0
18,2014Q3,-0.73,-0.52,26,79.0,60.0,30.0,49.0
19,2014Q4,-0.73,-0.52,26,79.0,60.0,30.0,49.0
20,2015Q1,-0.70,-0.55,27,79.0,59.0,30.0,47.0
21,2015Q2,-0.70,-0.55,27,79.0,59.0,30.0,47.0
22,2015Q3,-0.70,-0.55,27,79.0,59.0,30.0,47.0
23,2015Q4,-0.70,-0.55,27,79.0,59.0,30.0,47.0
24,2016Q1,-0.65,-0.52,29,79.0,57.0,30.0,47.0
25,2016Q2,-0.65,-0.52,29,79.0,57.0,30.0,47.0
26,2016Q3,-0.65,-0.52,29,79.0,57.0,30.0,47.0
27,2016Q4,-0.65,-0.52,29,79.0,57.0,30.0,47.0
28,2017Q1,-0.58,-0.48,30,79.0,62.0,30.0,48.0
29,2017Q2,-0.58,-0.48,30,79.0,62.0,30.0,48.0
30,2017Q3,-0.58,-0.48,30,79.0,62.0,30.0,48.0
31,2017Q4,-0.58,-0.48,30,79.0,62.0,30.0,48.0
32,2018Q1,-0.52,-0.36,32,80.0,63.0,30.0,52.0
33,2018Q2,-0.52,-0.36,32,80.0,63.0,30.0,52.0
34,2018Q3,-0.52,-0.36,32,80.0,63.0,30.0,52.0
35,2018Q4,-0.52,-0.36,32,80.0,63.0,30.0,52.0
36,2019Q1,-0.59,-0.37,30,82.0,66.0,30.0,52.0
37,2019Q2,-0.59,-0.37,30,82.0,66.0,30.0,52.0
38,2019Q3,-0.59,-0.37,30,82.0,66.0,30.0,52.0
39,2019Q4,-0.59,-0.37,30,82.0,66.0,30.0,52.0
40,2020Q1,-0.57,-0.38,33,81.0,61.0,30.0,55.0
41,2020Q2,-0.57,-0.38,33,81.0,61.0,30.0,55.0
42,2020Q3,-0.57,-0.38,33,81.0,61.0,30.0,55.0
43,2020Q4,-0.57,-0.38,33,81.0,61.0,30.0,55.0
44,2021Q1,-0.57,-0.40,32,89.0,64.0,30.0,56.0
45,2021Q2,-0.57,-0.40,32,89.0,64.0,30.0,56.0
46,2021Q3,-0.57,-0.40,32,89.0,64.0,30.0,56.0
47,2021Q4,-0.57,-0.40,32,89.0,64.0,30.0,56.0
48,2022Q1,-0.74,-0.64,33,74.0,61.0,30.0,54.0
49,2022Q2,-0.74,-0.64,33,74.0,61.0,30.0,54.0
50,2022Q3,-0.74,-0.64,33,74.0,61.0,30.0,54.0
51,2022Q4,-0.74,-0.64,33,74.0,61.0,30.0,54.0
52,2023Q1,-0.75,-0.58,36,NaN,NaN,NaN,NaN
53,2023Q2,-0.75,-0.58,36,NaN,NaN,NaN,NaN
54,2023Q3,-0.75,-0.58,36,NaN,NaN,NaN,NaN
55,2023Q4,-0.75,-0.58,36,NaN,NaN,NaN,NaN
56,2024Q1,-0.72,-0.60,35,NaN,NaN,NaN,NaN
57,2024Q2,-0.72,-0.60,35,NaN,NaN,NaN,NaN
58,2024Q3,-0.72,-0.60,35,NaN,NaN,NaN,NaN
59,2024Q4,-0.72,-0.60,35,NaN,NaN,NaN,NaN

# Final

In [14]:
final = school_enrollment.merge(df_q, on="year_quarter", how="inner")
final.to_csv("data/indicators_with_school_enrollment.csv", index=False)
final.head()

,year_quarter,school_enrollment_q_interp,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Fiscal freedom index (0-100),Business freedom index (0-100),Financial freedom index (0-100),Economic freedom overall index (0-100)
0,2010Q1,82.351502,-0.81,-0.81,24,78.0,39.0,30.0,46.0
1,2010Q2,82.203752,-0.81,-0.81,24,78.0,39.0,30.0,46.0
2,2010Q3,82.056001,-0.81,-0.81,24,78.0,39.0,30.0,46.0
3,2010Q4,81.908251,-0.81,-0.81,24,78.0,39.0,30.0,46.0
4,2011Q1,82.630715,-0.77,-0.83,23,77.0,47.0,30.0,46.0